language: python
sudo: true

python:
  - "3.6"
  - "3.7"
#  - "3.8"

addons:
  chrome: stable
#   apt:
#     packages:
#       - chromium-chromedriver

install:
  - pip install -r requirements.txt
  - pip install dash[testing]
  - pip install flake8

before_script:
  - CHROME_MAIN_VERSION=`google-chrome-stable --version | sed -E 's/(^Google Chrome |\.[0-9]+ )//g'`
  - CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAIN_VERSION"`
  - curl "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
  - unzip chromedriver_linux64.zip -d ~/bin
  #   - ln --symbolic /usr/lib/chromium-browser/chromedriver "${HOME}/bin/chromedriver"
  #   - ls ${HOME}/bin/
  - flask run & # Run in background, to run pytest next

script:
  - flake8 --max-line-length 120
  - pytest server/src/dashboard/tests --headless
#after_script: pkill -9 -f "autoapp.py"

