---
apiVersion: v1
kind: Namespace
metadata:
    name: openml-dev
    labels:
        environment: development

---
apiVersion: v1
kind: Namespace
metadata:
    name: openml-prod
    labels:
        environment: production
